name: Build, Test, and SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Use Linux-based runner for better compatibility

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # SonarQube analysis step
    - name: SonarQube Scan
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}  # This is your SonarQube server URL (e.g., https://sonarcloud.io for SonarCloud)
      run: mvn clean verify sonar:sonar \
            -Dsonar.projectKey=anshulspersona_capg_training \
            -Dsonar.host.url=sonarcloud.io \
            -Dsonar.login=6a8ec789efbc01ad9bdfbf3270a54444368290bd

    - name: Build Docker image
      run: docker build -t ghcr.io/${{ github.repository_owner }}/my-app:latest .

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push Docker image to GHCR
      run: docker push ghcr.io/${{ github.repository_owner }}/my-app:latest

    - name: Send email notification on success
      if: success()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.SMTP_USERNAME }}
        password: ${{ secrets.SMTP_PASSWORD }}
        subject: "Build Success: ${{ github.repository }}"
        body: |
          The build for repository ${{ github.repository }} was successful!
          Commit: ${{ github.sha }}
          Workflow: ${{ github.workflow }}
          Job: ${{ github.job }}
        to: "pisaca5419@coloruz.com"
        from: ${{ secrets.SMTP_USERNAME }}
